var app, client, cookieParser, etsyjs, express, server, session, url;

express = require('express');

session = require('express-session');

cookieParser = require('cookie-parser');

url = require('url');

etsyjs = require('etsy-js');

settings = require('./settings.json');

console.log(settings.key);

client = etsyjs.client({
  key: settings.key,
  secret: settings.secret,
  callbackURL: 'http://localhost:3010/authorise'
});

app = express();

app.use(cookieParser('secEtsy'));

app.use(session());

app.get('/', function(req, res) {
  return client.requestToken(function(err, response) {
    if (err) {
      return console.log(err);
    }
    req.session.token = response.token;
    req.session.sec = response.tokenSecret;
    return res.redirect(response.loginUrl);
  });
});

app.get('/authorise', function(req, res) {
  var query, verifier;
  query = url.parse(req.url, true).query;
  verifier = query.oauth_verifier;
  return client.accessToken(req.session.token, req.session.sec, verifier, function(err, response) {
    req.session.token = response.token;
    req.session.sec = response.tokenSecret;
    return res.redirect('/find');
  });
});

app.get('/find', function(req, res) {
  return client.auth(req.session.token, req.session.sec).user("etsyjs").find(function(err, body, headers) {
    if (err) {
      console.log(err);
    }
    if (body) {
      console.dir(body);
    }
    if (body) {
      return res.send(body.results[0]);
    }
  });
});

app.get("/createListing", function(req,res) {
  console.dir(req);
  console.dir(res);

  var newListing, oauthSession;
  oauthSession = {
    token: req.session.token,
    secret: req.session.sec
  };
  console.log("creating new listing...");
  newListing = {
    quantity: 1,
    title: "Example listing",
    description: "This is an awesome product!",
    price: 12.5,
    who_made: "collective",
    is_supply: true,
    when_made: "made_to_order",
    state: "draft"
  };

  return client.auth(oauthSession.token,oauthSession.secret).listing().createListing(newListing, function(err,body,headers) {
    if (err) {
      console.log(err);
    }
    if (body) {
      console.dir(body);
    }
    if (body) {
      return res.send(body.results[0]);
    }
  });


});

app.get('/createAddress', function(req, res) {
  var newAddress, oauthSession;
  oauthSession = {
    token: req.session.token,
    secret: req.session.sec
  };
  console.log("creating new address...");
  newAddress = {
    user_id: "etsyjs",
    name: "Etsy JS",
    first_line: "100 E8th St",
    city: "New York City",
    state: "New York",
    zip: "10009",
    country_id: 209
  };
  return client.auth(oauthSession.token, oauthSession.secret).address("etsyjs").create(newAddress, function(err, body, headers) {
    if (err) {
      console.log(err);
    }
    if (body) {
      console.dir(body);
    }
    if (body) {
      return res.send(body.results[0]);
    }
  });
});

server = app.listen(3010, function() {
  return console.log('Listening on port %d', server.address().port);
});

// ---
// generated by coffee-script 1.9.2
