var app, client, cookieParser, etsyjs, express, server, session, url;

express = require('express');

session = require('express-session');

cookieParser = require('cookie-parser');

url = require('url');

etsyjs = require('etsy-js');

client = etsyjs.client({
  key: '7w9x3xs3iz0ay80ul8ur1vjv',
  secret: 'ig3zc81yh6',
  callbackURL: 'http://localhost:3010/authorise'
});

app = express();

app.use(cookieParser('secEtsy'));

app.use(session());

app.get('/', function(req, res) {
  return client.requestToken(function(err, response) {
    if (err) {
      return console.log(err);
    }
    req.session.token = response.token;
    req.session.sec = response.tokenSecret;
    return res.redirect(response.loginUrl);
  });
});

app.get('/authorise', function(req, res) {
  var query, verifier;
  query = url.parse(req.url, true).query;
  verifier = query.oauth_verifier;
  return client.accessToken(req.session.token, req.session.sec, verifier, function(err, response) {
    req.session.token = response.token;
    req.session.sec = response.tokenSecret;
    return res.redirect('/find');
  });
});

app.get('/find', function(req, res) {
  return client.auth(req.session.token, req.session.sec).user("etsyjs").find(function(err, body, headers) {
    if (err) {
      console.log(err);
    }
    if (body) {
      console.dir(body);
    }
    if (body) {
      return res.send(body.results[0]);
    }
  });
});

server = app.listen(3010, function() {
  return console.log('Listening on port %d', server.address().port);
});

// ---
// generated by coffee-script 1.9.2
